# setup build on CI

if (FG_CI_BUILD)
	message( STATUS "configured CI build" )

	set( FG_ENABLE_OPENVR ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_TESTS ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_ASSIMP ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_GLM ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_DEVIL ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_IMGUI ON CACHE INTERNAL "" FORCE )
	set( FG_ENABLE_FFMPEG OFF CACHE INTERNAL "" FORCE )

	if (UNIX)
		set( FG_ENABLE_OPENVR OFF CACHE INTERNAL "" FORCE )
		set( FG_ENABLE_DEVIL OFF CACHE INTERNAL "" FORCE )
		set( FG_ENABLE_ASSIMP OFF CACHE INTERNAL "" FORCE )
		set( FG_ENABLE_GLM OFF CACHE INTERNAL "" FORCE )
	endif ()

endif ()
