
find_package( Git QUIET REQUIRED )

execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --dirty=+ --tags --always
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE FG_COMMIT_HASH
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE )

message( STATUS "FG_COMMIT_HASH: ${FG_COMMIT_HASH}" )

set_property( DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/.git/index" )
